services:
  bind9:
    image: ubuntu/bind9:latest
    container_name: bind9-server
    environment:
      - BIND9_USER=root
      - TZ=Europe/Vienna
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - '$BIND9_HOME/config:/etc/bind'
      - '$BIND9_HOME/cache:/var/cache/bind'
      - '$BIND9_HOME/records:/var/lib/bind'
    restart: unless-stopped