services:
  ldap:
    image: osixia/openldap:1.5.0
    command: --copy-service --loglevel debug
    container_name: ldap
    restart: unless-stopped
    hostname: 'ldap.nextgen.com'
    environment:
      - LDAP_ORGANISATION="Nextgen"
      - LDAP_DOMAIN=nextgen.com
      - LDAP_BASE_DN=dc=nextgen,dc=com
    ports:
      - '389:389'
      - '636:636'
    volumes:
      # TODO diese zu Paths auf dem Server mappen?
      # - /var/lib/ldap
      # - /etc/ldap/slapd.d
      # TODO Custom TLS-Cert?
      # - /container/service/slapd/assets/certs/
      - ./ldap-users.ldif:/container/service/slapd/assets/config/bootstrap/ldif/50-ldap-users.ldif
      - ./ldap-groups.ldif:/container/service/slapd/assets/config/bootstrap/ldif/51-ldap-groups.ldif
