services:
  gitlab:
    image: gitlab/gitlab-ce:18.4.5-ce.0
    container_name: gitlab
    restart: unless-stopped
    environment:
      GITLAB_ROOT_EMAIL: "admin@nextgen.com"
      GITLAB_ROOT_PASSWORD: "3<2KRiDj02FW"
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.30062022.xyz'
        nginx['listen_port'] = 80
        gitlab_rails['ldap_enabled'] = true
        gitlab_rails['ldap_servers'] = {
          'main' => {
            'label' => 'LDAP',
            'host' => 'ldap',
            'port' => 389,
            'uid' => 'uid',
            'method' => 'plain',
            'bind_dn' => 'cn=ldapuser,ou=users,dc=nextgen,dc=com',
            'password' => 'ldapuser',
            'timeout' => 10,
            'active_directory' => false,
            'user_filter' => '',
            'base' => 'ou=users,dc=nextgen,dc=com',
            'allow_username_or_email_login' => false,
            'group_base' => 'ou=groups,dc=nextgen,dc=com',
            'admin_group' => 'gitlab-admins',
          }
        }
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/srv/gitlab/config:/etc/gitlab'
      - '/srv/gitlab/logs:/var/log/gitlab'
      - '/srv/gitlab/data:/var/opt/gitlab'
  ldap:
    image: osixia/openldap:1.5.0
    command: --copy-service --loglevel debug
    container_name: ldap
    restart: unless-stopped
    hostname: 'ldap.nextgen.com'
    environment:
      - LDAP_ORGANISATION="Nextgen"
      - LDAP_DOMAIN=nextgen.com
      - LDAP_BASE_DN=dc=nextgen,dc=com
    ports:
      - '389:389'
      - '636:636'
    volumes:
      # TODO diese zu Paths auf dem Server mappen?
      # - /var/lib/ldap
      # - /etc/ldap/slapd.d
      # TODO Custom TLS-Cert?
      # - /container/service/slapd/assets/certs/
      - ./ldap-users.ldif:/container/service/slapd/assets/config/bootstrap/ldif/50-ldap-users.ldif
      - ./ldap-groups.ldif:/container/service/slapd/assets/config/bootstrap/ldif/51-ldap-groups.ldif
